# Generated by Django 5.1.1 on 2024-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=30)),
                ('Slot', models.TimeField()),
                ('Trainer', models.CharField(max_length=30)),
            ],
        ),
    ]
