# Generated by Django 5.1.1 on 2024-10-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_details',
            name='Slot',
            field=models.CharField(max_length=10),
        ),
    ]
