# Generated by Django 5.1.1 on 2024-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_stud_details_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=20)),
                ('Eid', models.CharField(max_length=10)),
            ],
        ),
    ]
