# Generated by Django 5.1.3 on 2024-11-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emp_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp_details',
        ),
        migrations.DeleteModel(
            name='stud_details',
        ),
    ]
